### ISSUE TITLE
没法控制

### ISSUE THREAD

**Issue by BayronP** [chanteP/ios-simulate-location-service#1]
请问第五步里面
pc可以上下左右控制，或者拖动操作面板控制方向和速度

为啥我用chrome打开了那个网页，没法控制啊

**Comment by chanteP** [comment]
咦，还真有其他人用啊（害怕
chrome打开控制台看一下报了什么错

**Comment by BayronP** [comment]
哈哈！是啊，最近腾讯出的一起来捉妖！ 我现在能用啦，上次是因为地图没刷出来！！

**Comment by BayronP** [comment]
就是这个AppleScript让我猝不及防哈哈
