### ISSUE TITLE
xcode脚本用不了

### ISSUE THREAD

**Issue by 329697166** [chanteP/ios-simulate-location-service#2]
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by chanteP** [comment]
没遇到过，xcode或者系统的问题可以goo一下..
https://stackoverflow.com/questions/51174105/pods-root-swiftlint-swiftlint-causes-command-phasescriptexecution-failed-w
https://juejin.im/post/5ba35cc05188255c7c655a8c
